language: generic 

services:
  - docker

before_install:
  - docker build -t artyomsidun/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true artyomsidun/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "docker"
  bucket_name: "elasticbeanstalk-eu-central-1-844847910395"
  bucket_path: "docker"
  on:
    branch:  main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY